version: "2"

services:
  percysnap:
    #build: .
    image: emcniece/percysnap:latest
    environment:
      PERCY_TOKEN: "${PERCY_TOKEN}"
      PERCY_TARGET_URL: "${PERCY_TARGET_URL}"
      PERCY_WAITFOR: body
      CRON_TIME: "${CRON_TIME}"
